### PR TITLE
Fixed server stop

### LINKED ISSUE #110: Can't properly stop lwt server
There appear to be two ways to stop a server started with `Conduit_lwt_unix.serve`, and neither seems to work correctly.
- If I pass `~stop` and wake up the stop thread, the server will accept the next connection and then exit its loop. However, the server thread never returns and the listening socket remains open.
- If I `Lwt.cancel` the server thread, the server immediately stops accepting connections and closes all existing connections. The server thread returns, but the listening socket remains open.

In both cases, I'm left with a listening socket that never accepts connections and prevents me from starting a new server on that port.

I think the correct behaviour in both cases is to close the listening socket when the accept loop exits, but I'm not sure why there are two mechanisms for this or what the intended differences are.

### PR DESCRIPTION
**Pull request by prepor**
It should fix #110, ie:
- Properly stops thread with server
- Eliminate fd leaks on server stop
- Does not create never-terminated tasks

### CODE REVIEW

**Comment by jerith** [comment]
Thanks for this!

I'm sadly not qualified to review it properly, but I'll definitely try it out later in the week to see if it fixes my problem.

**Comment by prepor** [comment]
Actually there is memory leak :) See https://github.com/ocsigen/lwt/issues/211
I'll rewrite it some other way.

**Comment by prepor** [comment]
I fixed memory leak

File: lib/conduit_lwt_unix.ml [hunk 1]
```diff
@@ -225,19 +225,19 @@ module Sockaddr_server = struct
...
+                  stop'] >>= function
+      | `Stop ->
+        Lwt.cancel accept;
+        Lwt.return_unit
+      | `Accept v ->
+        process_accept ?timeout callback v >>= fun () ->
         loop ()
     in
-    loop ()
+    Lwt.finalize loop (fun () -> Lwt_unix.close s)
```
Comment (avsm) [inline lib/conduit_lwt_unix.ml]: It would be better to explicitly close this socket in the `loop` -- why not call it in the `Stop` pattern match above rather than wait for the GC?

Comment (prepor) [inline lib/conduit_lwt_unix.ml]: Lwt.finalize is not about GC. It's just run `f` regardless of success or fail. If Lwt_unix.accept will fail for any reason `Stop code will not run.

**Comment by rgrinberg** [comment]
@avsm I think this is good. Do you have any objections to this?

@prepor Do you mind applying this to all lwt backends until we fix #112

**Comment by prepor** [comment]
@rgrinberg i'm sorry, but I currently not interested in this code, as I don't use lwt version of cohttp / conduit.

**Comment by avsm** [comment]
no objections to this, but would be really good to add a compose.yml test to test out server stop. I believe the Travis Docker runs compose.yml

**Comment by vbmithr** [comment]
Thanks!
